name: iceberg_lakehouse
version: "1.0.0"
config-version: 2

profile: lakehouse_duckdb

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ register_iceberg_sources() }}"

models:
  iceberg_lakehouse:
    staging:
      +materialized: view
    marts:
      +materialized: table
